version: '3.8'

services:
  app-dev:
    build:
      context: .
      target: development
    container_name: elight-lms-frontend-dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env.development
    environment:
      - NODE_ENV=development

  app-prod:
    build:
      context: .
      target: production
    container_name: elight-lms-frontend-prod
    ports:
      - "80:80"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production 